spring:
  cloud:
    gateway:
      routes:
      - id: block-actuator
        uri: no://op
        predicates:
        - Path=/actuator/health/**

      - id: pokemon-service
        uri: lb://pokemon-service
        predicates:
        - Path=/pokemon/**

    forwarded:
      enabled: true
